# Generated by Django 6.0.5 on 2026-08-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adoption', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída'), ('RETURNED', 'Devolvido')], default='IN_CHOICES', max_length=15)),
                ('date_devolution', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterAnimals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(choices=[('PUPPY', 'Filhote'), ('ADULT', 'Adulto'), ('SENIOR', 'Idoso')], max_length=15)),
                ('size', models.CharField(choices=[('LARGE', 'Grande'), ('SMALL', 'Pequeno')], max_length=15)),
                ('breed', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Macho'), ('FEMALE', 'Fêmea')], max_length=15)),
                ('color', models.CharField(max_length=20)),
                ('specie', models.CharField(choices=[('DOG', 'Cachorro'), ('CAT', 'Gato'), ('RABBIT', 'Coelho'), ('OTHER', 'Outro')], max_length=15)),
                ('temperament', models.CharField(choices=[('CALM', 'Calmo'), ('PLAYFUL', 'Brincalhão'), ('ACTIVE', 'Ativo'), ('SHY', 'Tímido')], max_length=15)),
                ('good_with_children', models.BooleanField(default=False)),
                ('good_with_dogs', models.BooleanField(default=False)),
                ('good_with_cats', models.BooleanField(default=False)),
                ('neutered', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
                ('animal_photo', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('RESERVED', 'Reservado'), ('ADOPTED', 'Adotado')], default='AVAILABLE', max_length=15)),
            ],
        ),
    ]
