# Generated by Django 6.0.5 on 2026-08-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tutorprofile'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tutorprofile'),
        ),
        migrations.AddField(
            model_name='registeranimals',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ongprofile'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.registeranimals'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.registeranimals'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('animal', 'tutor')},
        ),
    ]
